### ISSUE TITLE
Passing part of multidimension array to subroutine does not copy back

### ISSUE THREAD

**Issue by Leporacanthicus** [flang-compiler/f18-llvm-project#1001]
When trying to make SNAP run, I found that some values were not calculated correctly. Printing many different variables and comparing their values with gfortran, turns out that one variable is definitely not correctly filled in - it stays the original initial value of zero. 

I made a much simpler reproducer:
```PROGRAM p

  INTERFACE 
     SUBROUTINE fillme( a )
       REAL, DIMENSION(3, 3), INTENT(OUT) :: a
     END SUBROUTINE fillme
  END INTERFACE
  
  REAL, DIMENSION(3, 3, 3) :: d

  d = 2.0
  CALL fillme( d(:,:, 1) )
  print *, "d=", d
END PROGRAM p


SUBROUTINE fillme( a )
  REAL, DIMENSION(3, 3), INTENT(OUT) :: a
  a = 1.0

  print *, "A=", a
END SUBROUTINE fillme
```

The generate MLIR at the moment is not making any attempt to copy the values back:

```
  %22 = fir.allocmem !fir.array<3x3xf32>
  %23 = fir.shape %10, %11 : (index, index) -> !fir.shape<2>
  %24 = fir.array_load %22(%23) : (!fir.heap<!fir.array<3x3xf32>>, !fir.shape<2>) -> !fir.array<3x3xf32>
  %c1_9 = constant 1 : index
  %c0_10 = constant 0 : index
  %25 = subi %10, %c1_9 : index
  %26 = subi %11, %c1_9 : index
  %27 = fir.do_loop %arg0 = %c0_10 to %26 step %c1_9 unordered iter_args(%arg1 = %24) -> (!fir.array<3x3xf32>) {
    %41 = fir.do_loop %arg2 = %c0_10 to %25 step %c1_9 unordered iter_args(%arg3 = %arg1) -> (!fir.array<3x3xf32>) {
      %42 = fir.array_fetch %21, %arg2, %arg0, %18 : (!fir.array<3x3x3xf32>, index, index, index) -> f32
      %43 = fir.array_update %arg3, %42, %arg2, %arg0 : (!fir.array<3x3xf32>, f32, index, index) -> !fir.array<3x3xf32>
      fir.result %43 : !fir.array<3x3xf32>
    }
    fir.result %41 : !fir.array<3x3xf32>
  }
  fir.array_merge_store %24, %27 to %22 : !fir.array<3x3xf32>, !fir.array<3x3xf32>, !fir.heap<!fir.array<3x3xf32>>
  %28 = fir.convert %22 : (!fir.heap<!fir.array<3x3xf32>>) -> !fir.ref<!fir.array<3x3xf32>>
  fir.call @_QPfillme(%28) : (!fir.ref<!fir.array<3x3xf32>>) -> ()
  fir.freemem %22 : !fir.heap<!fir.array<3x3xf32>>
```

I'm trying to look at what generates this code and see if I can fix it, but I'm not holding that much hope... It's not OBVIOUS where this code generation happens.

**Comment by jeanPerier** [comment]
>I'm trying to look at what generates this code and see if I can fix it, but I'm not holding that much hope... It's not OBVIOUS where this code generation happens.

Thanks for the bug report. The code doing the copy-in copy-out is here:
https://github.com/flang-compiler/f18-llvm-project/blob/e6485383b651c66456ca0f245116bacedbf4de03/flang/lib/Lower/ConvertExpr.cpp#L1855-L1864

Given the allocmem (%22 in your dump) does not have the ".copyinout" attribute, I suspect the issue is that the code is not falling into the if, but lowering still evaluate the expression in a temp. It is worth double checking, but I think `d(:,:, 1)` is contiguous, so the issue most likely lies in `genExtAddr` making a temp for `d(:, :, 1)` even when `Fortran::evaluate::IsSimplyContiguous` returned true one the expression.

**Comment by Leporacanthicus** [comment]
Thanks Jean! I'll take a look and see what I can find. There may be more than one bug, as I also thought it should just calculate the address and pass the original address [+ offset if required].

**Comment by Leporacanthicus** [comment]
I believe the problem is that the code unconditionally creates a temporary copy of the array, based on this callstack (cleaned up version of what GDB gives):
```
ArrayExprLowering::createAndLoadSomeArrayTemp (this=0x7fffffff9998, type=..., shape=...) at flang/lib/Lower/ConvertExpr.cpp:3413
ArrayExprLowering::genIterSpace (this=0x7fffffff9998, resultType=...) at flang/lib/Lower/ConvertExpr.cpp:3275
ArrayExprLowering::lowerArrayExpression(std::function<fir::ExtendedValue ((anonymous namespace)::ArrayExprLowering::IterationSpace const&)>, mlir::Type) (this=0x7fffffff9998, f=..., resultTy=...) at flang/lib/Lower/ConvertExpr.cpp:2765
<removed several layers of calls that just forward from one layer to the next - with very long function names>
ArrayExprLowering::lowerArrayExpression (this=0x7fffffff9998, exp=...) at flang/lib/Lower/ConvertExpr.cpp:2735
ArrayExprLowering::lowerSomeNewArrayExpression (converter=..., symMap=..., stmtCtx=..., shape=..., expr=...) at flang/lib/Lower/ConvertExpr.cpp:2655
Fortran::lower::createSomeArrayTempValue (converter=..., shape=..., expr=..., symMap=..., stmtCtx=...) at flang/lib/Lower/ConvertExpr.cpp:5591
ScalarExprLowering::asArray<Fortran::evaluate::Expr<Fortran::evaluate::SomeType> > (this=0x7fffffffc880, x=...) at flang/lib/Lower/ConvertExpr.cpp:2160
ScalarExprLowering::gen<Fortran::evaluate::SomeType> (this=0x7fffffffc880, x=...) at flang/lib/Lower/ConvertExpr.cpp:2199
ScalarExprLowering::genExtAddr (this=0x7fffffffc880, expr=...) at flang/lib/Lower/ConvertExpr.cpp:270
ScalarExprLowering::genRawProcedureRef(Fortran::evaluate::ProcedureRef const&, llvm::Optional<mlir::Type>)::{lambda()#1}::operator()() const (this=0x7fffffffb470) at flang/lib/Lower/ConvertExpr.cpp:1868
ScalarExprLowering::genRawProcedureRef (this=0x7fffffffc880, procRef=..., resultType=...) at flang/lib/Lower/ConvertExpr.cpp:1853
```
I think the code doesn't actually understand that it just needs a reference, and makes a separate object no matter what (and also doesn't understand it needs to copy back!). I'm yet to understand how to fix this.

**Comment by Leporacanthicus** [comment]
By the way, not slicing (is that the right word?) the array works fine:

```
PROGRAM p

  INTERFACE 
     SUBROUTINE fillme( a )
       REAL, DIMENSION(3, 3), INTENT(OUT) :: a
     END SUBROUTINE fillme
  END INTERFACE
  
  REAL, DIMENSION(3, 3) :: d

  d = 2.0
  CALL fillme( d )
  print *, "d=", d
END PROGRAM p


SUBROUTINE fillme( a )
  REAL, DIMENSION(3, 3), INTENT(OUT) :: a
  a = 1.0

  print *, "A=", a
END SUBROUTINE fillme
```

**Comment by jeanPerier** [comment]
I think the issue is that `gen(expr)` is making a copy and the code in genRawProcedure was expecting to not get a temp for expr for which "IsVariable(*expr) && IsContiguous(*expr)" is true.

gen(expr) is indeed not creating a temp based on a different logic [here](https://github.com/flang-compiler/f18-llvm-project/blob/344abfa696345c125cc8aaad9b4634ab1f743e63/flang/lib/Lower/ConvertExpr.cpp#L2175).

The logic in gen(expr) makes sense given how array expression is set-up. ScalarExprLowering::genref() is not set-up to deal with array slices, even if they are simply contiguous, it can only deal with whole array symbol reference.

So you can fix the logic by:
1. Using gen(expr) logic in genRawProcedure  (replace IsContiguous by UnwrapWholeSymbolOrComponentDataRef). This will create a copy-in/copy-out as expected, but is a bit of a waste since there is no reason to create a copy in/out from a functional point of view if we could avoid making a copy.
2. Upgrade  gen(expr) to not make a copy for variable that are simply contiguous. Lowering avoids as much as possible to expose offset computations an uses high level FIR ops to deal with array slices (fir.array_coor, fir.embox ...). One way to compute the base address of the slice in lowering could to create a box for the expression (a Fortran descriptor), and read back the box base address and extents. (So in gen(expr), for the simply contiguous variables, you could create a box (with lowerBoxedArrayExpression or similar), and then, based on the knowledge that it is contiguous, get rid of thefir.box (descriptor) with `fir::factory::readBoxValue`).

**Comment by Leporacanthicus** [comment]
I'm closing this, it seems to be working for me (and I reported it!)
