### ISSUE TITLE
One bug? The variable in main program should implicitly have save attribute.

### ISSUE THREAD

**Issue by PeixinQiao** [flang-compiler/f18-llvm-project#1093]
Here is the test case.
```
program main
  integer :: a4, arr4(10)
  integer, save :: a5, arr5(10)
contains
  subroutine sub6()
    integer :: a6, arr6(10)
    integer, save :: a7, arr7(10)
  end
end
```
I run this code using `bbc` in `fir-dev` with commit `2af3c27c0f5ceec3a1e225d90955d17efc457543` on aarch64. The result is as follows
```
$ bbc -emit-fir test.f90 && cat test.mlir
func @_QQmain() {
  %0 = fir.alloca i32 {bindc_name = "a4", uniq_name = "_QEa4"}    // This is wrong?
  return
}
func @_QPsub6() {
  %0 = fir.alloca i32 {bindc_name = "a6", uniq_name = "_QFsub6Ea6"}
  %1 = fir.alloca !fir.array<10xi32> {bindc_name = "arr6", uniq_name = "_QFsub6Earr6"}
  return
}
fir.global internal @_QEa5 : i32 {
  %0 = fir.undefined i32
  fir.has_value %0 : i32
}
fir.global internal @_QEarr4 : !fir.array<10xi32> {
  %0 = fir.undefined !fir.array<10xi32>
  fir.has_value %0 : !fir.array<10xi32>
}
fir.global internal @_QEarr5 : !fir.array<10xi32> {
  %0 = fir.undefined !fir.array<10xi32>
  fir.has_value %0 : !fir.array<10xi32>
}
fir.global internal @_QFsub6Ea7 : i32 {
  %0 = fir.undefined i32
  fir.has_value %0 : i32
}
fir.global internal @_QFsub6Earr7 : !fir.array<10xi32> {
  %0 = fir.undefined !fir.array<10xi32>
  fir.has_value %0 : !fir.array<10xi32>
}
```
According to Fortran 2018 standard [8.5.16], a variable, common block, or procedure pointer declared in the scoping unit of a main program, module, or submodule implicitly has the SAVE attribute, which may be confirmed by explicit specification. Should it generate `fir.global` with `internal` attribute for the variable `a4` instead of `fir.alloca`?

**Comment by jeanPerier** [comment]
Is it causing functional issues ?

Array and character variables in main programs are lowered to fir.global (the logic doing this is [here](https://github.com/flang-compiler/f18-llvm-project/blob/4f77995f9b8b320467303bb73a5ffac4b0b44f94/flang/lib/Lower/PFTBuilder.cpp#L1327-L1348), through the reentrant flag that is false for main programs) because they can be big and stack allocation is limited, but for simple variable, it was not clear this was needed.
AFAIK, Fortran standard does not say variables with the SAVE attribute should be in global memory. In practice, it is needed to use global memory outside of the MAIN program to implements the SAVE requirements from 8.5.16. But it is not clear to me how a program could legally access a variable after the MAIN program returned.

**Comment by PeixinQiao** [comment]
@jeanPerier No, there is no functional issue. I care about this since it is related to the lowering work of OpenMP `threadprivate` directive. The variable in `threadprivate` directive must have the SAVE attribute, either implicitly or explicitly. I need to add the OpenMP `threadprivate` attribute in FIR Operation Def. If `fir.global` is generated for the simple variable in MAIN program, I only need to change GlobalOp in FIR. Otherwise, AllocOp also needs to be changed.

Anyway, it is strange to generate `fir.alloca` for `integer :: a4` and `fir.global` for `integer, save :: a5` in MAIN program, although they both work well.

**Comment by PeixinQiao** [comment]
Checked with classic-flang and it generates `local alloc` for `integer :: a4` and `struct.BSS` for `integer, save :: a5` in MAIN program, which is similar to `bbc`. Let me add the OpenMP threadprivate attribute in both `GlobalOp` and `AllocOp`. Close this issue.

**Comment by jeanPerier** [comment]
Thanks for having checked that the classic Flang behavior was the same here !

**Comment by shraiysh** [comment]
This issue is causing the design of OpenMP Dialect in MLIR to become complicated. I will be reopening this issue because while it does not cause any functional issues, if forces special handling for this specific case. If this is meant as an optimization, this can be done as an FIR pass, which will probably not modify the IR if this was also used by OpenMP operations.

**Comment by jeanPerier** [comment]
Note that the `-fno-automatic` causes all main program variables to implicitly have the save attribute (including scalars). I am not sure if it makes sense having OpenMP requiring this flag (it also affects locals in non recursive programs), but you could also consider it.

**Comment by PeixinQiao** [comment]
I don't think adding `-fno-automatic` is one good way. It may cause performance issues for some local arrays if we want to use it in stack. Besides, it makes flang not compatible with gfortran regarding to this option.

**Comment by shraiysh** [comment]
> Edit: on second thought, you most likely do not want to use it outside of the main program to run things in parallel
I don't think adding -fno-automatic is one good way. It may cause performance issues for some local arrays if we want to use it in stack. Besides, it makes flang not compatible with gfortran regarding to this option.

Right, would it be okay @jeanPerier to do this change for the variables to make the behavior consistent and avoid special cases?

**Comment by schweitzpgi** [comment]
In short, it is not wrong and is the intended default. The main program is not reentrant. Any RETURN from the main program can never "come back" to another instance of the main program. For performance reasons, we want to register promote variables, even in the main program. (Imagine aggressively inlining into the main program. It would be a bad idea to force every variable's value to travel back and forth through memory each time it was potentially updated.) Stack allocation is consistent with other Fortran implementations here.

There are a few command line options to control the behavior. @jeanPerier mentioned one of them above.

I don't see how TLS has any bearing on this actually. Can you explain further? A stack allocated variable is already TLS and it does not need to be coerced in any special way.

**Comment by sscalpone** [comment]
> This issue is causing the design of OpenMP Dialect in MLIR to become complicated

Please explain the issue and complication.

**Comment by PeixinQiao** [comment]
> I don't see how TLS has any bearing on this actually. Can you explain further? A stack allocated variable is already TLS and it does not need to be coerced in any special way.

That's right. Actually classic-flang generates alloca in main program in LLVM IR for threadprivate directive and emits the openmp runtime call with the argument of alloca result. I have transformed the allocaOp into GlobalOp for threadprivate variables with implicit SAVE attribute in main program to simplify the [lowering](https://github.com/Huawei-PTLab/f18-llvm-project/blob/2f93243b5f7c401241b1fd0d0a4cc183b607f302/flang/lib/Lower/OpenMP.cpp#L933-L938). With @schweitzpgi considering the performance issues, I think we can transform into GlobalOp for threadprivate varaibles and leave other variables emiting AllocaOp.

> There are a few command line options to control the behavior.

I don't think using some options doing this is one good way. Using the current [code](https://github.com/Huawei-PTLab/f18-llvm-project/blob/2f93243b5f7c401241b1fd0d0a4cc183b607f302/flang/lib/Lower/OpenMP.cpp#L933-L938) to do the transformation is the most clean method.

> Please explain the issue and complication.

We did a lot of discussions for threadprivate, and I think we have some discussion gap here and somewhere in the PR. It is not only this issue causing the design of OpenMP dialect in MLIR becoming complicated. It is this issue with host-assocation usage causing.

**Comment by shraiysh** [comment]
I will try to elaborate the issue and the suggested solution.
AFAIU for all cases of threadprivate we can have a global variable with a thread_local attribute and then start using it like any normal variable in the program. The problem with the current implementation of implicit SAVE (passing a local reference to the function as an argument) is that we lose information that it is a global and hence while trying to add threadprivate, we have relax threadprivate allow any reference, and we cannot we depend on thread_local anymore. This forces us to find other ways to accommodate any reference into the threadprivate operation.

The proposed solution -
I understand the performance issues, and my suggestion was to move the variable to stack as a frontend pass instead of codegen for FIR. When the global is used in omp.threadprivate operations, such a pass would not run thus ensuring correctness for OpenMP and performance for Fortran both. By having the consistency of globals with thread_local we also enforce the necessary restrictions on threadprivate by design which saves us from unexpected code generation.

Please let me know if anything isn't clear or if something seems incorrect.

**Comment by PeixinQiao** [comment]
> I understand the performance issues, and my suggestion was to move the variable to stack as a frontend pass instead of codegen for FIR.

As in my mind, there are four solutions to handle this:
1. Add `SAVE` attribute for threadprivate variables in semantic analysis.
2. Add global attribute when making `Variable` for threadprivate variables.
3. instantiate `Global` when `Variable` is global or symbol has threadprivate flag.
4. Do it using current implementation.

For 1 and 2, I am not sure if it is reasonble and if it will crash some code. For 3, it is kind of intruding FIR codegen. For 4, the code is kind of redundant, but the openmp is isolated with FIR. All in all, all have pros and cons. What do you think? @jeanPerier @schweitzpgi
