### ISSUE TITLE
Undefined reference when compiling ll files with clang -O2

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#1095]
This version of flang uses clang to compiler ll files and for linking.  The -O2 flag is passed to clang; it doesn't affect flang.
```
% cat s1.f90
module ggg
  integer :: vvv
end
```
```
% cat s2.f90
use ggg
  vvv = 1
end
```
```
% flang s?.f90
%
```
```
% flang -O2 s?.f90
/bin/ld: s2.o: in function `_QQmain':
s2.f90:2: undefined reference to `_QMgggEvvv'
clang-13: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by Leporacanthicus** [comment]
I started looking into this from a different source, using `opt` to optimise the code, which leads to the same issues [since `opt` probably uses largely the same set of set of optimization passes as `clang`). I did find some way to specify only "some" of the passes, but that's not a good long term solution [and didn't give the results I expected].

**Comment by sscalpone** [comment]
```
; ModuleID = 'FIRModule'
source_filename = "FIRModule"

@_QMgggEvvv = linkonce global i32 undef
```
> Unreferenced linkonce globals are allowed to be discarded.
https://llvm.org/docs/LangRef.html#linkage

Probably needs to be "external" instead of "linkonce".

**Comment by Leporacanthicus** [comment]
My quick-fix, insert `sed 's/linkonce global/dso_local global/g`  between tco and opt - I expect that would work when using clang as the compiler too. I couldn't make "external" work - maybe I'm doing something wrong - I just  used clang++ as "reference that works", and it uses `dso_local` to indicate that this is "once per executable file" variable [or something like that - I'm really just hacking this, as my goal right now isn't to fix this issue permanently, but work around the fact that we want to run with optimization enabled in a script.

Once I have some results (should be soon!), I'd be happy to help with the correct solution - I tried just changing linkonce in flang, but then tco won't read the mlir input, and I gave up at that point.

**Comment by sscalpone** [comment]
What did you see with "external"?

**Comment by Leporacanthicus** [comment]
> What did you see with "external"?

opt didn't like reading the modified IR.
```
/data/f18-llvm-project/build/bin/opt: global.mod.ll:4:43: error: expected top-level entity
@_QMglobal_moduleEx = external global i32 undef
                                          ^
```

Arrow is pointing at `undef` - I think external really means "it's not in this module, it's somewhere else, so you have to initialize it somewhere else". But I'm the first to admit I don't REALLY know what I'm doing here! :)

**Comment by jeanPerier** [comment]
@Leporacanthicus 

`@_QMglobal_moduleEx = external global i32 undef` is indeed wrong syntax, the correct equivalent is `@_QMglobal_moduleEx =  global i32 undef` the external is implicit when there is a definition.

I used `linkonce` because I could not get mlir to generate this. Its LLVM IR generation was transforming `@_QMglobal_moduleEx =  global i32 undef`  into `@_QMglobal_moduleEy =  external global i32`, which did not even made it through llc.
So it should be considered there might also be wrong with the mlir LLVM IR generation.

I am not sure dso_local is needed and how it will travel through MLIR.

As far as I remember, the MLIR logic that removes the undef is in shouldDropGlobalInitializer [here](https://github.com/llvm/llvm-project/blob/bdaf038266c28a67bce83491dafd6752e53d4e33/mlir/lib/Target/LLVMIR/ModuleTranslation.cpp#L541). If you blame it, you'll see my name, but I only refactored this code a while back to fix another bug, so it is unclear to me why MLIR is dropping the undef.

**Comment by jeanPerier** [comment]
Good news, the MLIR behaviour changed in https://github.com/llvm/llvm-project/commit/d4df3825bd32277074b3859f5dea9593139147fb#diff-0e9fd6478c7a83100254a3b40e2d97649a8d41c84506e1da7f8d281fc633b1f5. So I think the fix is just not create external with undef variable, this should now travel through MLIR and have the correct behavior.

@Leporacanthicus do you want to give a try at this fix ?

**Comment by Leporacanthicus** [comment]
So with Jean Perier's recommended patch from llvm/main, and using an empty string instead of the `linkonce` attribute, my tests are working (as discussed on Flang Slack). I will try to produce a patch that fixes the comments as well as failing tests - unless someone else already has a fix in progress.

**Comment by jeanPerier** [comment]
> unless someone else already has a fix in progress.

No I am working on other patches so I am grateful if you do the patch for it (I imagine it indeed involves doing some sed s/linkonce//g in the tests).  Thanks !

**Comment by Leporacanthicus** [comment]
This is now merged, @sscalpone  please re-open if the current fix is not working.

**Comment by sscalpone** [comment]
Thanks!  I'll let you know.
