### ISSUE TITLE
`flang` wrapper script deletes object code that should not be deleted

### ISSUE THREAD

**Issue by jeffhammond** [flang-compiler/f18-llvm-project#1348]
I have a module that is used by every file in my project.  Every program needs to link the object file associated with that module.

Flang is deleting the module object file.  This breaks all of my builds.

```
jhammond@nuclear:~/PRK/FORTRAN$ /usr/local/bin/flang -c prk_mod.F90 
jhammond@nuclear:~/PRK/FORTRAN$ ll *mod*
-rw-rw-r-- 1 jhammond jhammond  394 Dec 15 14:00 prk.f18.mod
-rw-rw-r-- 1 jhammond jhammond  603 Dec 15 14:00 prk.mod
-rw-rw-r-- 1 jhammond jhammond 2.1K Dec 15 12:58 prk_mod.F90
-rw-rw-r-- 1 jhammond jhammond 5.5K Dec 15 14:00 prk_mod.o
jhammond@nuclear:~/PRK/FORTRAN$ /usr/local/bin/flang -g -O3 -ffast-math -Wall  -DRADIUS=2 -DSTAR transpose.F90 prk_mod.o -o transpose
jhammond@nuclear:~/PRK/FORTRAN$ ll *mod*
-rw-rw-r-- 1 jhammond jhammond  394 Dec 15 14:00 prk.f18.mod
-rw-rw-r-- 1 jhammond jhammond  603 Dec 15 14:00 prk.mod
-rw-rw-r-- 1 jhammond jhammond 2.1K Dec 15 12:58 prk_mod.F90
```

I can see that Flang is trying to delete my object file below:
```
jhammond@nuclear:~/PRK/FORTRAN$ /usr/local/bin/flang -c prk_mod.F90 
jhammond@nuclear:~/PRK/FORTRAN$ ll *mod*
-rw-rw-r-- 1 jhammond jhammond  394 Dec 15 14:02 prk.f18.mod
-rw-rw-r-- 1 jhammond jhammond  603 Dec 15 14:02 prk.mod
-rw-rw-r-- 1 jhammond jhammond 2.1K Dec 15 12:58 prk_mod.F90
-rw-rw-r-- 1 jhammond jhammond 5.5K Dec 15 14:02 prk_mod.o
jhammond@nuclear:~/PRK/FORTRAN$ chmod -w prk_mod.o
jhammond@nuclear:~/PRK/FORTRAN$ ll *mod*
-rw-rw-r-- 1 jhammond jhammond  394 Dec 15 14:02 prk.f18.mod
-rw-rw-r-- 1 jhammond jhammond  603 Dec 15 14:02 prk.mod
-rw-rw-r-- 1 jhammond jhammond 2.1K Dec 15 12:58 prk_mod.F90
-r--r--r-- 1 jhammond jhammond 5.5K Dec 15 14:02 prk_mod.o
jhammond@nuclear:~/PRK/FORTRAN$ /usr/local/bin/flang -g -O3 -ffast-math -Wall  -DRADIUS=2 -DSTAR transpose.F90 prk_mod.o -o transpose
rm: remove write-protected regular file 'prk_mod.o'? n
jhammond@nuclear:~/PRK/FORTRAN$ ll *mod*
-rw-rw-r-- 1 jhammond jhammond  394 Dec 15 14:02 prk.f18.mod
-rw-rw-r-- 1 jhammond jhammond  603 Dec 15 14:02 prk.mod
-rw-rw-r-- 1 jhammond jhammond 2.1K Dec 15 12:58 prk_mod.F90
-r--r--r-- 1 jhammond jhammond 5.5K Dec 15 14:02 prk_mod.o
```

`rm: remove write-protected regular file 'prk_mod.o'?` is outrageous.  Flang should not delete files that were generated by a separate process.

I can see where this happens in the driver.  I modified it as below...

```
  # Delete intermediate object files
  for idx in "${!fortran_source_files[@]}"; do
    echo "JEFF" rm "${object_files[$idx]}"
    rm "${object_files[$idx]}"
  done
```
...and this is the result...
```
jhammond@nuclear:~/PRK/FORTRAN$ /usr/local/bin/flang -g -O3 -ffast-math -Wall  -DRADIUS=2 -DSTAR transpose.F90 prk_mod.o -o transpose
JEFF rm prk_mod.o
rm: remove write-protected regular file 'prk_mod.o'? n
```

This is the attribution of this code:
```
e77191c35e334 flang/tools/f18/flang.in (Andrzej Warzynski 2021-07-01 09:33:00 +0100 454)   # Delete intermediate object files
e77191c35e334 flang/tools/f18/flang.in (Andrzej Warzynski 2021-07-01 09:33:00 +0100 455)   for idx in "${!fortran_source_files[@]}"; do
739f49ed12a4d flang/tools/f18/flang.in (Andrzej Warzynski 2021-07-07 11:41:45 +0100 456)     rm "${object_files[$idx]}"
e77191c35e334 flang/tools/f18/flang.in (Andrzej Warzynski 2021-07-01 09:33:00 +0100 457)   done
```

@banach-space I'd like to understand why the driver is doing this, but more importantly, for it to be changed to not do this.

**Comment by banach-space** [comment]
Hi @jeffhammond ,

[`flang-new` - compiler driver]
[`flang` - bash wrapper script]

Thanks for submitting this and for your very detailed reproducer. I'm sorry that this is not working as expected.

Before diving any deeper - why not use the actual [driver](https://github.com/llvm/llvm-project/blob/main/flang/docs/FlangDriver.md#flang-drivers) instead of the [bash wrapper script](https://github.com/llvm/llvm-project/blob/main/flang/docs/FlangDriver.md#the-flang-script)? The bash script is not actively developed and is only meant as a temporary workaround. As it requires an external Fortran compiler to work (e.g. `gfortran`), there are no in-tree tests to validate it. As Flang's compiler driver has recently gained the ability to generate executable, the bash script is no longer needed (unless you really want to use `gfortran` for code-generation). Why not use the driver instead of the wrapper script?

As for the bash script, it has never been meant as an actual compiler driver. Indeed, Bash is not really suitable to write one :)  When implementing `flang` (the bash script), our goal was to replace the previous driver, `f18`. As a result, not all compiler use cases are supported as robustly as a typical compiler driver would (e.g. Flang's compiler driver, `flang-new`).

I was able to reproduce the issue that you are hitting. From a quick glance, the script assumes that `object_files` will only contain temporary object files **generated by the script** (and which can be safely deleted). But in your case,  `prk_mod.o` is a user input and should not be included in `object_files`. There should probably be `temp_object_files` and `user_object_files` instead of just `object_files`.

I won't have the bandwidth to look into this before January, but I should be able to help if you decide to fix it yourself. If you are able to use `flang-new` instead, then that might be the best approach here.

Thank you,
-Andrzej

**Comment by jeffhammond** [comment]
I tried `flang-new` but I cannot figure out how to generate executables.  Do you know what I am doing wrong?
```
/usr/local/bin/flang-new  -c prk_mod.F90 -o prk_mod.o
error: code-generation is not available yet
```

**Comment by banach-space** [comment]
Where did you get `flang` and `flang-new` from? From the invocation that you've pasted, I'm guessing that this might from a distro binary package. That would be too old. LLVM Flang is under active development and code-gen support has only been added recently. Basically, you need to build from sources. Please make sure that you are building the "fir-dev" branch.

-Andrzej

**Comment by jeffhammond** [comment]
I built Flang from Git using https://github.com/jeffhammond/HPCInfo/blob/master/buildscripts/llvm-git.sh yesterday, but with https://github.com/flang-compiler/f18-llvm-project.git instead of upstream.

I was not, however, on the fir-dev branch.  Will use that now.

**Comment by banach-space** [comment]
Uploaded a fix: https://reviews.llvm.org/D116590
