### ISSUE TITLE
Bug about upper bound in pointer association

### ISSUE THREAD

**Issue by PeixinQiao** [flang-compiler/f18-llvm-project#1521]
```
  integer, pointer :: a(:,:,:)
  integer, target :: b(-1:-2,-3:-4,-4:-6)
  integer :: uba(3), ubb(3)
  a=>b
  uba = ubound(a)
  ubb = ubound(b)
  !print *, ubound(a), ubound(b)
  if (uba(1) /= ubb(1)) stop 1
  if (uba(2) /= ubb(2)) stop 2
  if (uba(3) /= ubb(3)) stop 3
  print *, "PASS"
end
```
Expected:
```
$ flang-new test.f90 && ./a.out
PASS
```
Result:
```
$ flang-new test.f90 && ./a.out
Fortran STOP: code 3
```

**Comment by jeanPerier** [comment]
Thanks for reporting the bug.
It looks like a double UBOUND bug when the extent is zero: one in the front-end folding, and one in lowering.

**Expected behavior:**
As per the standard (16.9.196 UBOUND Case(i)):
_"If DIM is present, ARRAY is a whole array, and dimension DIM of ARRAY **has nonzero extent**, [...]. Otherwise, if DIM is present, the result has a value equal to the number of elements in dimension DIM of ARRAY."_
Hence, both `ubound(a)` and `ubound(b)` should be `[0, 0 , 0]`.

**Bugs**
Both the front-end folding of UBOUND and lowering or UBOUND are ignoring this aspect, in a different manner. The front end folding uses the subscripts: `[-2, -4, -6]` (this is what is used for `ubound(b)` since it is folded), and lowering is using `lb + extent -1`, leading to `lb-1` if the extents are zero (`[-2, -4, -5]`).

I will fix both parts.

**Comment by jeanPerier** [comment]
Hi @PeixinQiao , this bug should be fixed now. Please close it whenever you are able to verify the fix.

**Comment by PeixinQiao** [comment]
Tested ok now.
