### ISSUE TITLE
`--always-execute-loop-body` should also force unstructured loops

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#214]
implementation is only for structured loops. Unstructured loops should probably also be forced to have 1 iteration using the same switch.

**Comment by schweitzpgi** [comment]
It is a typical non-standard feature for a Fortran compiler to have a switch to allow the user to force the body of a DO loop to be executed at least once, even when there are zero iterations.

**Comment by schweitzpgi** [comment]
Sameeran taking a look.

**Comment by Sameeranjoshi** [comment]
I can have a small code snippet for checking the unstructured loops, but I am facing issue in writing test for `tco`
So writing a test for `tco` for a program like 
```
program some
        implicit none
        integer :: i,j
        do i=542,542,1
                print *, "In goto loop"
                goto 10
        end do
10 j=20
end program

```
I think we need to convert the fortran program to `fir` using `--emit-fir` to `bbc`, this is fine, but the code generated doesn't have any `fir.loop`, does that happen due to unstructured loops which have a complex control flow giving rise to basic blocks?

Also the FIR generated is too big, so is there any pointers on how to do testing of `tco` and that too for loops (unstructured)?
