### ISSUE TITLE
omp-barrier.f90 test fails

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#250]
********************
Failed Tests (1):
  Flang :: Lower/omp-barrier.f90

**Comment by schweitzpgi** [comment]
@SouraVX -- code did not survive the rebase

**Comment by SouraVX** [comment]
I think this is seen after
e3d3feb9d8e8f98ff9aa15dd7e284f655ffaf78f
@schweitzpgi do you accidentally forgot to remove those **#if 0** blocks. 

But the actual root cause trace back to this: 2ddba3082ca79080b14f372ebe4b5bdbc5f694ed
[flang][openmp] Use common Directive and Clause enum from llvm/Frontend

OmpSimpleStandaloneDirective was ENUM_CLASS is refactored to WRAPPER_CLASS_BOILERPLATE.

**Comment by SouraVX** [comment]
@schweitzpgi Could you please share your thought/plans if any regarding whether we should upstream it. Otherwise we might have to deal with this sort of downstream failures/bugs lately.
Thanks!

**Comment by schweitzpgi** [comment]
Go ahead and upstream the parts that make sense.

Thanks!
