### ISSUE TITLE
sinh and max1 not recognized as intrinsics (fm308)

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#285]

**Comment by jeanPerier** [comment]
This is an issue in the front-end: if an intrinsic function appears in a type declaration statement, we consider this is an external function.
Minimal reproducer:
```
  REAL :: ACOS
  PRINT *, ACOS(0.5)
END
```

`f18 -debug-dump-symbols` output is `acos (Function) size=24 offset=0: ProcEntity REAL(4)` instead of `acos, INTRINSIC (Function): ProcEntity`.

It is legal for an intrinsic to appear in a type declaration statement according to F2018 standard section 8.2 point 3:
>  A name that identifies a specific intrinsic function has a type as specified in 16.8. An explicit type declaration statement is not
required; however, it is permitted. Specifying a type for a generic intrinsic function name in a type declaration statement has no effect.

**Comment by tskeith** [comment]
This is fixed by https://reviews.llvm.org/D84702 in llvm-project.

**Comment by sscalpone** [comment]
passes.
