### ISSUE TITLE
csin correctness fm820

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#341]
```
./fm820.out > fm820.log
Fortran STOP
IEEE arithmetic exceptions signaled: INEXACT
diff fm820.log .//ref/fm820.log
27,38c27,30
<      5     FAIL  
<                  COMPUTED= (     0.99929,     -0.99929)
<                  CORRECT=  (     1.88709,      0.06024)
<      6     FAIL  
<                  COMPUTED: ( 0.94898E+00,  0.94898E+00)
<                  CORRECT:  ( 0.23021E+09,  0.76492E+08)
<      7     FAIL  
<                  COMPUTED= (     0.00000,      0.00000)
<                  CORRECT=  (     0.00000,      1.17520)
<      8     FAIL  
<                  COMPUTED= (     0.00000,      0.00000)
<                  CORRECT=  (     0.00000,    -57.78782)
---
>      5     PASS  
>      6     PASS  
>      7     PASS  
>      8     PASS  
52,63c44,47
<     14     FAIL  
<                  COMPUTED= (     0.03760,      0.03760)
<                  CORRECT=  (     0.07101,     -1.60079)
<     15     FAIL  
<                  COMPUTED: ( 0.31532E+00,  0.31532E+00)
<                  CORRECT:  ( 0.76492E+08, -0.23021E+09)
<     16     FAIL  
<                  COMPUTED= (     1.00000,      1.00000)
<                  CORRECT=  (     1.54308,      0.00000)
<     17     FAIL  
<                  COMPUTED= (     1.00000,      1.00000)
<                  CORRECT=  (    57.79647,      0.00000)
---
>     14     PASS  
>     15     PASS  
>     16     PASS  
>     17     PASS  
69,70c53,54
<                          10 TESTS PASSED
<                           9 TESTS FAILED
---
>                          18 TESTS PASSED
>                           1 TESTS FAILED
```

**Comment by schweitzpgi** [comment]
More complex intrinsics. CSIN here.

**Comment by sscalpone** [comment]
At least on x86, the abi specifies that complex is passed as a short struct, which means that the value is shoved in an xmm register.

I'm looking at a short example:

```
      complex c
      external mysin
      complex mysin
      c = (2.0, 1.0)
      c = mysin(c)
      end
```

The fir looks good:
`  %4 = fir.call @_QPmysin(%0) : (!fir.ref<!fir.complex<4>>) -> !fir.complex<4>
`

The resulting mlir does not look correct because  it is passing the complex as two floats, which doesn't translate into the short struct calling convention:
`  %9 = llvm.call @_QPmysin(%5) : (!llvm<"{ float, float }*">) -> !llvm<"{ float, float }">
`
And the resulting llvm ir:
`  %2 = call { float, float } @_QPmysin({ float, float }* %1), !dbg !10
`

Here you can see how clang generates llvm ir for a similar C program:
`  %call = call <2 x float> @mysin(<2 x float> %1)
`

The small struct return follows a similar convention.

**Comment by sscalpone** [comment]
The key takeaway is that the lowering to mlir is losing the representation of the structured type, either that of mlir complex or struct { ... }.

**Comment by schweitzpgi** [comment]
This is an instance of how flang's handling of complex needs to be wedded to the actual target.

**Comment by schweitzpgi** [comment]
duplicate #344
