### ISSUE TITLE
correctness fm403 -- variation in output

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#442]
```
diff fm403.log .//ref/fm403.log
355c355
<                                    0.10  0.0099E+06 987654.0039
---
>                                  987.66  0.0099E+06     98.7654
361c361
<                                9.88E+02  0.0086E+06        0.86
---
>                                9.88E+02  0.0086E+06     8647.86
make: [fm403.run] Error 1 (ignored)
```

**Comment by jeanPerier** [comment]
IO runtime issue with scale factor (P descriptor). It looks like the runtime is scaling acording to -k instead of k. Reproducer:
```
      REAL A
      A = 1.
70560 FORMAT (1PF12.2)
      WRITE (06,70560) A
      END
```
Prints `0.10` when it should print `10.` When using  `FORMAT (-1PF12.2)`, this is the reverse, `10.` is printed instead of `0.10`.

With gdb break points in the compiled program at `_FortranAioBeginExternalFormattedOutput` I can see that the format argument is `(1pf12.2)` and formatlength is 9 as expected. So it looks like the issue lies in the IO runtime.

**Comment by schweitzpgi** [comment]
See also #384

**Comment by sscalpone** [comment]
Pass.  Verified.
