### ISSUE TITLE
Canonicalize trivial IF statement structures into IF constructs

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#478]
Currently semantics can canonicalize labeled DO statements into DO constructs (see https://github.com/flang-compiler/f18-llvm-project/blob/master/flang/lib/Semantics/canonicalize-do.cpp). For example:

```fortran
   DO 2 i = 1,10
      ...
2 CONTINUE
```
will be (effectively) rewritten to
```fortran
   DO i = 1,10
      ...
   END DO
```

A similar rewrite is possible for localized IF statements.

```fortran
   IF (.not. cond) GOTO 2
   ...code...
2 CONTINUE
```
can be rewritten as the IF construct
```fortran
   IF (cond) THEN
     ...code...
   END IF
```

**Comment by vdonaldson** [comment]
Doing this canonicalization will typically avoid generation of a block containing just a branch, and may allow generation of a structured `fir.if` operation.  Either of these could result in better code.

This canonicalization can be done in at least three different places in the compiler, each of which may have various advantages and disadvantages.  There is also an interrelated tradeoff between the amount of compile time spent on looking for candidate cases, vs. the number of cases than can be canonicalized.  The following example illustrates this.  Subroutine `s1` contains two overlapping canonicalization candidates, involving labels `11` and `22`.  f18 and other compilers translate `s1` correctly without warnings or errors.  All compilers also all handle the canonicalization of the label `11` case without warnings or messages as illustrated by subroutine `s2`.  Compiler behavior for canonicalization of the label `22` case in subroutine `s3` produces a varied response, from no messages, to warnings, to hard errors.  The execution result of compilers that don't abort with an error is as expected.  It is impossible to canonicalize both the label `11` and label `22` cases.

Canonicalizing `s1 -> s2` is arguably the preferred choice; choosing `s1 -> s3` is a poor choice.  The more relevant question is whether to attempt the `s1 -> s2` canonicalization at all.  To state the issue another way, the constraints on `label-do -> nonlabel-do` canonicalization guarantee that it will succeed.  By contrast, `if` canonicalizations are sometimes impossible or illegal, and there may be a tradeoff between how much compile time is spent on determining that canonicalization is valid, vs. the number of cases that are selected for canonicalization.

```
subroutine s1(jj, kk) ! no warnings/errors
   if (jj == 1) goto 11
   kk = kk + 1
   if (jj == 2) goto 22
   kk = kk + 10
11 kk = kk + 100
22 kk = kk + 1000
end

subroutine s2(jj, kk) ! no warnings/errors
   if (jj /= 1) then
     kk = kk + 1
     if (jj == 2) goto 22
     kk = kk + 10
   endif
11 kk = kk + 100
22 kk = kk + 1000
end

subroutine s3(jj, kk)
   if (jj == 1) goto 11 ! possible illegal branch warning/error
   kk = kk + 1
   if (jj /= 2) then
     kk = kk + 10
11   kk = kk + 100
   endif
22 kk = kk + 1000
end

   k = 0; call s1(0, k); print*, k
   k = 0; call s1(1, k); print*, k
   k = 0; call s1(2, k); print*, k

   print*
   k = 0; call s2(0, k); print*, k
   k = 0; call s2(1, k); print*, k
   k = 0; call s2(2, k); print*, k

   print*
   k = 0; call s3(0, k); print*, k
   k = 0; call s3(1, k); print*, k
   k = 0; call s3(2, k); print*, k
end
```

**Comment by vdonaldson** [comment]
This functionality is implemented by making the control flow modifications when building the PFT, but deferring the condition negation until FIR generation.  That allows use of front end parse tree contents without modification, while allowing branch analysis to operate on the modified IR.  Incoming code without overlapping conversion candidates will successfully convert all candidates, which may in turn be materialized as fir.if ops, subject to usual branch analysis conditions.  Code with overlapping candidates, such as example routine s1, use a simple heuristic to select candidates to convert.  Those heuristic choices will in general not be candidates for materialization as fir.if ops due to the conflicts, so that heuristic choice is probably not very significant.  However, that selection code can easily be changed to favor other conflicting conversion candidates.
