### ISSUE TITLE
error: expected floating point type

### ISSUE THREAD

**Issue by sscalpone** [flang-compiler/f18-llvm-project#505]
```
% cat gq.f
      subroutine test03 ()
      real ( kind = 10 ) x
      x = 1.0
      return
      end
```
```
% bbc gq.f |& head
error: expected floating point type
bbc: /local/home/sjs/mirror/fir-dev-mirror/mlir/include/mlir/IR/StorageUniquerSupport.h:91: static ConcreteT mlir::detail::StorageUserBase<ConcreteT, BaseT, StorageT, UniquerT, Traits>::get(mlir::MLIRContext*, Args ...) [with Args = {mlir::Type, llvm::APFloat}; ConcreteT = mlir::FloatAttr; BaseT = mlir::Attribute; StorageT = mlir::detail::FloatAttributeStorage; UniquerT = mlir::detail::AttributeUniquer; Traits = {}]: Assertion `succeeded(ConcreteT::verifyConstructionInvariants( generateUnknownStorageLocation(ctx), args...))' failed.
PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
Stack dump:
0.      Program arguments: bbc gq.f
 #0 0x00005629dd869edd llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/local/home/sjs/mirror/install/bin/bbc+0x345dedd)
 #1 0x00005629dd867c14 llvm::sys::RunSignalHandlers() (/local/home/sjs/mirror/install/bin/bbc+0x345bc14)
 #2 0x00005629dd867d80 SignalHandler(int) (/local/home/sjs/mirror/install/bin/bbc+0x345bd80)
 #3 0x00007ff5f07448a0 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x128a0)
 #4 0x00007ff5ef3b0f47 raise /build/glibc-2ORdQG/glibc-2.27/signal/../sysdeps/unix/sysv/linux/raise.c:51:0
```

**Comment by jeanPerier** [comment]
FIR/MLIR limitation. I think we are stuck creating constant for floating point types not supported by mlir (REAL(10) and REAL(16), mlir has f16, bf16, f32, f64.)

`mlir::Builder:: getFloatAttr(Type type, const APFloat &value);` is called with `type = fir.real<10>`.
From their documentation, it seems mlir::FloatAttr requires mlir floating point types, that does not include the one we need for real(10).
We hit an assertion that calls verifyFloatTypeInvariants that expect that `type` is an mlir::FloatType (and not fir::realType):
https://github.com/llvm/llvm-project/blob/69efcd03bdb9ee7328dd4e75513ae214c1e23519/mlir/lib/IR/Attributes.cpp#L253

I see three solution:
1. Create a fir attribute to store floating point constant for all fir real types, but since it will not be supported by mlir::ConstantOp, we will also need to add a fir::ConstantOp to support this.
2. Directly use LLVM dialect attributes and types to create the constant, then cast back to fir::real type so that we can work with.
3. Extend mlir to support f80 and f128 floating point types. This would allow us to take advantage of mlir fp ops without having to duplicate them for the type they do not support and we want to support.

**Comment by schweitzpgi** [comment]
Alex has added support in LLVM IR dialect for these types, but as you correctly point out they are missing from standard dialect. And all the underpinning interplay between them may not be worked out. Have to ping the MLIR guys about this again, probably.

**Comment by schweitzpgi** [comment]
I should've mentioned that we already added `fir.constf` as an Op because of this situation.

**Comment by schweitzpgi** [comment]
This still requires a solution on the Tilikum side.

**Comment by sscalpone** [comment]
Verified that the error msg is gone.

**Comment by schweitzpgi** [comment]
Now lowers to
```mlir
func @_QPtest03() {
  %cst = constant 1.000000e+00 : f32
  %0 = fir.alloca f80 {name = "_QFtest03Ex"}
  %1 = fir.convert %cst : (f32) -> f80
  fir.store %1 to %0 : !fir.ref<f80>
  return
}
```
