### ISSUE TITLE
[OpenMP] RTL function call names getting mangled

### ISSUE THREAD

**Issue by SouraVX** [flang-compiler/f18-llvm-project#611]
```
program main
use omp_lib
!$OMP PARALLEL
print*, omp_get_thread_num()
!$OMP END PARALLEL
end

$bbc parallel.f90 -fopenmp -I /build/tools/flang/include/flang/ -o -  | egrep "omp_get_thread_num"
    %10 = fir.call @_QPomp_get_thread_num() : () -> i32
func private @_QPomp_get_thread_num() -> i32

**Comment by SouraVX** [comment]
For tracking, FYI @kiranchandramohan

**Comment by SouraVX** [comment]
Can anyone please provide pointers WRT this issue ?
Thanks!

**Comment by jeanPerier** [comment]
> Can anyone please provide pointers WRT this issue ?

I did not dwell into the issue, but I am pretty sure this is because BIND(C) attributes is not taken into account in the name mangling. Not sure if we just want to ignore mangling in this case or if we need a special mangling here.
The idea of the mangling, on top of avoiding conflicts, is that one can find back the scope/symbols from the mangled name. So if we just ignore the mangling, that might prevent that.
