### ISSUE TITLE
Loop variable can't be used after $!omp parallel do.

### ISSUE THREAD

**Issue by Leporacanthicus** [flang-compiler/f18-llvm-project#667]
Compiling the attached file with `bbc -fopenmp simple.f90` gives an error:

```
error: loc("./simple.f90":11:3): 'fir.store' op operand #1 must be any reference, but got 'i32'
oops, pass manager reported failure
```
Problem goes away if I use a new variable name for the checking loop at the bottom. It also goes away if you remove the `-fopenmp`.

Obviously, the file should be called "simple.f90", but the UI forbids uploading .f90 files, so added .txt to make it "acceptable"
[simple.f90.txt](https://github.com/flang-compiler/f18-llvm-project/files/6108249/simple.f90.txt)

**Comment by kiranchandramohan** [comment]
Thanks @Leporacanthicus for reporting this issue. 

This issue was pointed out by @jeanPerier in https://github.com/flang-compiler/f18-llvm-project/pull/646#discussion_r584602652. The issue was fixed by https://github.com/flang-compiler/f18-llvm-project/pull/652 and https://github.com/flang-compiler/f18-llvm-project/pull/646. I believe a build from the current fir-dev branch should not show this issue. If you feel this issue is fixed then please close.

**Comment by Leporacanthicus** [comment]
Yes, with an updated code-base it doesn't go wrong any longer (I think #652 is the one fixing this particular issue)
