### ISSUE TITLE
maxval intrinsic missing

### ISSUE THREAD

**Issue by schweitzpgi** [flang-compiler/f18-llvm-project#83]
bbc lapack/SRC/sbdsvdx.f

(LAPACK sources from https://github.com/Reference-LAPACK/lapack.git)

```
  7%] Building Fortran object SRC/CMakeFiles/lapack.dir/sbdsvdx.f.o
LLVM ERROR: missing intrinsic: maxval

PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace.
...
```

See also dbdsvdx.f

**Comment by zacharyselk** [comment]
If no one else is working on this I would like to give it a go.

**Comment by jeanPerier** [comment]
Hi Zachery, MAXVAL is free to take, however, it is not entirely doable currently because the intrinsic library does not work with arrays yet. It first needs:
- https://github.com/flang-compiler/f18-llvm-project/pull/75 that brings a way to propagate arrays inside the bridge
- Then, the intrinsic lowering framework will have to be updated to use this ExtendedValue instead of exchanging value.

If you still want to go for this one right now, you could start thinking of an implementation for it assuming you would have to code something like:
`ExtendedValue IntrinsicLibrary::genMaxval(ExtendedValue& array, ExtendedValue* dim, ExtendedValue* mask)` in https://github.com/flang-compiler/f18-llvm-project/blob/fir-dev/flang/lib/Lower/Intrinsics.cpp. where `ExtendedValue` is a new class defined in #75.
The actual interface might turn-out to be a bit different, but it should be easy to patch this.

**Comment by zacharyselk** [comment]
Good to know. I guess I will tinker around with a tentative implementation until lowering framework is updated. Thanks for the heads up!

**Comment by schweitzpgi** [comment]
Update: #75 was merged.

**Comment by schweitzpgi** [comment]
see #84
